package core

type Capability string

const (
	CapabilityTradingAuthSendOTP       Capability = "trading.auth.send_otp"
	CapabilityTradingAuthTradingToken  Capability = "trading.auth.trading_token"
	CapabilityTradingAccountsList      Capability = "trading.accounts.list"
	CapabilityTradingAccountsBalance   Capability = "trading.accounts.balance"
	CapabilityTradingBuyingPower       Capability = "trading.accounts.buying_power"
	CapabilityTradingLoanPackages      Capability = "trading.accounts.loan_packages"
	CapabilityTradingOrdersList        Capability = "trading.orders.list"
	CapabilityTradingOrdersHistory     Capability = "trading.orders.history"
	CapabilityTradingOrdersGet         Capability = "trading.orders.get"
	CapabilityTradingOrdersPlace       Capability = "trading.orders.place"
	CapabilityTradingOrdersCancel      Capability = "trading.orders.cancel"
	CapabilityTradingOrdersReplace     Capability = "trading.orders.replace"
	CapabilityTradingOrdersExecutions  Capability = "trading.orders.executions"
	CapabilityTradingPositionsList     Capability = "trading.positions.list"
	CapabilityTradingPositionsGet      Capability = "trading.positions.get"
	CapabilityTradingPositionsClose    Capability = "trading.positions.close"
	CapabilityTradingRealtimeOrders    Capability = "trading.realtime.orders"
	CapabilityTradingRealtimePosition  Capability = "trading.realtime.positions"
	CapabilityTradingConditionalOrders Capability = "trading.conditional_orders"
	CapabilityTradingCashTransfer      Capability = "trading.cash.transfer"
	CapabilityTradingStockTransfer     Capability = "trading.stock.transfer"
	CapabilityBrokerageCareBy          Capability = "brokerage.accounts.care_by"
	CapabilityMarketDataSymbolsList    Capability = "marketdata.symbols.list"
	CapabilityMarketDataQuotes         Capability = "marketdata.quotes.snapshot"
	CapabilityMarketDataCandles        Capability = "marketdata.candles.history"
	CapabilityMarketDataRealtimeTicks  Capability = "marketdata.realtime.ticks"
	CapabilityMarketDataRealtimeTop    Capability = "marketdata.realtime.top_price"
	CapabilityMarketDataRealtimeCandle Capability = "marketdata.realtime.candles"
	CapabilityMarketDataRealtimeRaw    Capability = "marketdata.realtime.raw"
)
