package fhsc

import (
	nativemarketdata "github.com/vnbrokers/vnbrokers-go/brokers/fhsc/native/marketdata"
	nativetrading "github.com/vnbrokers/vnbrokers-go/brokers/fhsc/native/trading"
	"github.com/vnbrokers/vnbrokers-go/core"
)

var Capabilities = []core.Capability{
	core.CapabilityTradingAuthSendOTP,
	core.CapabilityTradingAccountsBalance,
	core.CapabilityTradingBuyingPower,
	core.CapabilityTradingPositionsList,
	core.CapabilityTradingOrdersList,
	core.CapabilityTradingOrdersHistory,
	core.CapabilityTradingOrdersGet,
	core.CapabilityTradingOrdersPlace,
	core.CapabilityTradingOrdersCancel,
	core.CapabilityTradingOrdersReplace,
	CapabilityGetCurrentUser,
	CapabilityGetSubAccounts,
	CapabilityVerifyTwoFactor,
	CapabilityRevokeTwoFactor,
	nativemarketdata.CapabilityGetBankInterestRates,
	nativemarketdata.CapabilityGetCompanyFinancialAnalysis,
	nativemarketdata.CapabilityGetCompanyFinancialOverview,
	nativemarketdata.CapabilityGetTopTrendingCryptos,
	nativemarketdata.CapabilityGetEconomicCalendarEvents,
	nativemarketdata.CapabilityGetFinancialData,
	nativemarketdata.CapabilityGetFinancialStatementV2,
	nativemarketdata.CapabilityGetGrowthBenchmark,
	nativemarketdata.CapabilityGetNAVBenchmark,
	nativemarketdata.CapabilityGetFundCompanies,
	nativemarketdata.CapabilityGetFundSuggestions,
	nativemarketdata.CapabilityGetFundMonths,
	nativemarketdata.CapabilityGetFundNAVHistories,
	nativemarketdata.CapabilityGetFundPortfolio,
	nativemarketdata.CapabilityGetFundCertificates,
	nativemarketdata.CapabilityGetGlobalNewsList,
	nativemarketdata.CapabilityGetGlobalNewsDetail,
	nativemarketdata.CapabilityGetGoldChartData,
	nativemarketdata.CapabilityGetGoldProviderData,
	nativemarketdata.CapabilityGetGoldData,
	nativemarketdata.CapabilityGetIndexRealtime,
	nativemarketdata.CapabilityGetMacroData,
	nativemarketdata.CapabilityGetMarketData,
	nativemarketdata.CapabilityGetMetalProviderData,
	nativemarketdata.CapabilityGetStockEvents,
	nativemarketdata.CapabilityGetPriceHistoriesChart,
	nativemarketdata.CapabilityGetRecommendationReports,
	nativemarketdata.CapabilityGetSilverChartData,
	nativemarketdata.CapabilityGetSilverData,
	nativemarketdata.CapabilityGetStockRealtime,
	nativemarketdata.CapabilityGetTradingEconomicsData,
	nativetrading.CapabilityGetAccountSummary,
	nativetrading.CapabilityGetUserAssetsSummary,
	nativetrading.CapabilityGetPnLToday,
	nativetrading.CapabilityGetPortfolio,
	nativetrading.CapabilityGetAvailableTrade,
	nativetrading.CapabilityGetOrderHistory,
	nativetrading.CapabilityGetOrderBookDetail,
	nativetrading.CapabilityGetUserRights,
	nativetrading.CapabilityGetMarketSession,
}
